---
title: An Introduction to R
author: Filip Schouwenaars, DataCamp
output: beamer_presentation
---

## About DataCamp

- Online Data Science School
- Trained +230,000 data science professionals
    + finance, marketing, technology, etc.
- Video lessons and coding challenge
    + In-browser, self-paced
- Instructors from Princeton, Microsoft, RStudio, Duke, etc.
- www.datacamp.com/demo

## About the Workshop

- Basic intro to R
- Case Study
- Questions? Yes, please!

## R

- Language for Statistical Computing
- New Zealand, 90s
- Open source
- Command-Line > Point and click
- Share code through R scripts and packages
- Huge vibrant online community
- Has to fit in the main memory

## Use Python instead?

- Both have loads of reliable libraries
- R: get results fast
- Python: more work, but more customization possible
- R wins when it comes to visualization
- Python is a 'fuller' programming language

## How we use R for marketing

- Dashboards
    + Users
    + Subscribers
    + Revenue
    + Churn
- The "aha" moment
- Analysis of email campaigns
- ...

## Get Started

- Install R & RStudio
- Download zip: 

