---
title: An Introduction to R
author: Filip Schouwenaars, DataCamp
output: ioslides_presentation
---

## About DataCamp

- Online Data Science School
- > 500,000 registered users
- Video lessons and coding challenges
    + In-browser, self-paced
- World class instructors

## We're hiring

- Always looking for smart people
- Still studying? No worries!
- Get in touch: filip@datacamp.com

## About the Workshop

- Basic intro to R
- Case Study 1: maps data
- Case Study 2: machine learning
- Questions? Yes please!

## R

- Language for Statistical Computing
- New Zealand, 90s
- Open source
- Command-Line > Point and click
- Share code through R scripts and packages
- Huge vibrant online community
- Great for visualization
- Has to fit in the main memory

## Get Started!

- Install R: https://cran.rstudio.com/
- Install RStudio, an IDE: https://www.rstudio.com/products/rstudio/download/
- Download zip: [bit.ly/2eDMr8h](bit.ly/2eDMr8h) or on [GitHub](https://github.com/filipsch/r-workshop)
- Unzip
- Open up RStudio
- Set working directory to point to unzipped folder


