---
title: An Introduction to R
author: Filip Schouwenaars, DataCamp
output: ioslides_presentation
---

## About DataCamp

- Online Data Science School
- > 600,000 registered users
- Video lessons and coding challenges
    + In-browser, self-paced
- World-class instructors
- [www.datacamp.com/demo](www.datacamp.com/demo)

## We're hiring

- Always looking for smart people
- Mainly computer scientists
- Still studying? No problem!
- Get in touch: filip@datacamp.com

## About the Workshop

- Intro to R and Python
- Try R and Python on DataCamp
- Case Study 1: Data exploration
- Case Study 2: Machine learning
- You can follow along
- Questions? Yes please!

## R & Python

| R       | Python |
| ------- | ------ |
| New Zealand, 90s | Netherlands, 90s |
| Open source | Open source |
| Command-Line > Point and click | Command-line > Point and click |
| Share code through R scripts and packages | Share code through Python scripts and package |
| Visualization | Production-ready applications |
| Has to fit in the main memory | Fully fledged programming language |

## Get Started!

- Install R: https://cran.rstudio.com/
- Install RStudio, an IDE: https://www.rstudio.com/products/rstudio/download/
- Install Python: https://www.continuum.io/downloads
- Download files and unzip
  - Bitly link: **bit.ly/2gzwYYz**
  - Github: **github.com/filipsch/workshop**



